{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.externalSecrets[0].name }}
  namespace: {{ .Values.externalSecrets.externalSecrets[0].namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.externalSecrets[0].name }}
  data:
    {{- range .Values.externalSecrets.externalSecrets }}
    - secretKey: {{ .secretKey }}
      targetKey: {{ .targetKey }}
    {{- end }}
{{- end }}
---
